version: "3.9"
services:
  prompushgateway:
    image: "prom/pushgateway"
    ports:
      - "9091:9091"
  prometheus:
    image: "prom/prometheus"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    depends_on: 
      - prompushgateway            
  grafana:
    image: "grafana/grafana:8.1.2"
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-storage:/var/lib/grafana
    depends_on: 
      - prometheus   
